# Generated by Django 5.1.6 on 2025-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
