# Generated by Django 5.2.1 on 2025-09-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.BigIntegerField(unique=True, verbose_name='Matricula'),
        ),
    ]
